version: '2'

services:
    server:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}_server
        links:
            - php
        ports:
            - 80:80
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
            # - ./config/nginx/sites-enabled/local.magento.com.br.conf:/etc/nginx/conf.d/local.magento.com.br.conf
            - ./config/nginx/includes:/etc/nginx/includes
            - ./config/nginx/custom-locations:/etc/nginx/custom-locations
        volumes_from:
            - php
        # group_add:
        #    - wheel
        #    - www-data
    php:
        #image: andreaskoch/dockerized-magento-php
        #image: php:5.6-fpm
        #image: php:5.6-fpm-alpine
        build:
            context: ./images/php
            dockerfile: Dockerfile-7.0
        container_name: ${PROJECT_NAME}_php
        links:
            - database
            - cache
            - session
        volumes:
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
            #- ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            #- ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./web:/var/www/html
        # group_add:
        #    - wheel
        #    - www-data
    database:
        image: percona:latest
        container_name: ${PROJECT_NAME}_database
        volumes:
            - database_data:/var/lib/mysql
            # - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: magento
            MYSQL_ROOT_PASSWORD: magento
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
    cache:
        image: redis:alpine
        container_name: ${PROJECT_NAME}_cache
    session:
        image: redis:alpine
        container_name: ${PROJECT_NAME}_session
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: ${PROJECT_NAME}_phpmyadmin
        links:
            - database
        ports:
            - 8080:80
        environment:
            MYSQL_ROOT_PASSWORD: magento
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: magento
            PMA_PASSWORD: magento
volumes:
    database_data:
