version: '2'

services:
    web:
        container_name: ${PROJECT_NAME}_web
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            # - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
            - ./config/nginx/sites-enabled/local.magento.com.br.conf:/etc/nginx/conf.d/local.magento.com.br.conf
            # - ./config/nginx/includes:/etc/nginx/includes
            # - ./config/nginx/custom-locations:/etc/nginx/custom-locations
        volumes_from:
            - appdata:ro
        depends_on:
            - php
        networks:
            - front
            - back

    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: ./images/php
            dockerfile: Dockerfile-7.0
        volumes:
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
            #- ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            #- ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./web:/var/www/html
        volumes_from:
            - appdata
        depends_on:
            - appdata
            - database
            # - cache
            # - session
        # user: www-data
        networks:
            - back


    appdata:
        image: alpine:latest
        container_name: ${PROJECT_NAME}_source
        volumes:
            - ./config/appdata/startup.sh:/startup.sh
            - ./web:/var/www/html
        # command: /bin/sh /startup.sh


    database:
        image: percona:latest
        container_name: ${PROJECT_NAME}_database
        volumes:
            - database_data:/var/lib/mysql
            # - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: magento
            MYSQL_ROOT_PASSWORD: magento
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
        networks:
            - back


    cache:
        image: redis:alpine
        container_name: ${PROJECT_NAME}_cache
        networks:
            - back

    session:
        image: redis:alpine
        container_name: ${PROJECT_NAME}_session
        networks:
            - back

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: ${PROJECT_NAME}_phpmyadmin
        links:
            - database
        ports:
            - 8080:80
        environment:
            MYSQL_ROOT_PASSWORD: magento
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: magento
            PMA_PASSWORD: magento
        networks:
            - front
            - back

networks:
    front:
        driver: bridge
    back:
        driver: bridge

volumes:
    database_data:
        driver: local
